spring:
  profiles:
    active: 
    -test
---
spring:
  profiles:
    active: test
  application:
    name: luosteel-test
---
spring:
  profiles:
    active: dev
  application:
    name: luosteel-123
