spring:
  profiles:
    active: 8761
  application:
    name: server
eureka:
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # fal8se 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
---
spring:
  profiles: 8763
server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/,http://eureka8761.com:8761/eureka/
  instance:
    hostname: eureka8763.com
---
spring:
  profiles: 8762
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://eureka8763.com:8763/eureka/,http://eureka8761.com:8761/eureka/
  instance:
    hostname: eureka8762.com
---
spring:
  profiles: 8761
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://eureka8763.com:8763/eureka/,http://eureka8761.com:8761/eureka/
  instance:
    hostname: eureka8761.com